### ISSUE TITLE
Add individuals chart functionality to the package

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/autospc#101]
Enable use of I-charts (individuals charts) in autospc. This is a sub-issue of #75.

**Comment by HorridTom** [comment]
The first step of this is to integrate the `get_i_limits` function into the main algorithm. E.g. by including the I and mr charts in [this](https://github.com/HorridTom/autospc/blob/09ca25c3f4d8d68c38d7a75f55dd012e4e7813e7/R/functions.R#L109-L120) `if` statement. There is one more as well.

**Comment by Comfortti** [comment]
The X portion of the XmR chart is fully integrated, next step is to simultaneously plot both the X chart and the mR chart when the user calls to plot an XmR chart. 

For test driven development, a test needs to be written where the final result is that both the X-chart and MR-chart are displayed simultaneously using ggplot2 and cowplot (renv needs to be updated to add cowplot too). 

The mR chart needs to be dependent on the X-chart in terms of sharing the same x-axis, containing the same breakPoints and plotPeriods as the X-chart, similarly to the attached image:

![XmR Chart Example](https://github.com/HorridTom/autospc/assets/56454834/eea9c05c-0237-4a12-a11b-5b4249a39eb3)
