### ISSUE TITLE
Add test for floating median line

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/autospc#129]

**Comment by Comfortti** [comment]
@HorridTom when possible, may I get clarification about when the median line calculation/plotting get triggered?

**Comment by HorridTom** [comment]
@Comfortti Thanks for this, good question!

The `plot_auto_SPC` function has two arguments that are relevant here: `floatingMedian` and `floatingMedian_n`

If `floatingMedian` is "yes", then a median of the final `floatingMedian_n` points should be displayed

If `floatingMedian` is "auto", then a median should be plotted _if_ at least one point of the final `floatingMedian_n` points is part of a shift (rule 2) break, and _not_ otherwise. If plotted, again the median should be of the final `floatingMedian_n` points.

If `floatingMedian` is not "yes" or "auto", no median should be plotted.

Hope this makes sense, if not let me know!
