### ISSUE TITLE
Roxygen skeleton to include examples.

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/autospc#18]

**Comment by HorridTom** [comment]
The first step of this would be to identify a suitable example dataset to include with the package. We could use an example dataset comprising some of the publicly available A&E data, perhaps anonymised. Ultimately might want to add several datasets to support examples for various different chart types, but a good start would be to add one. This should be done in line with [https://r-pkgs.org/data.html](https://r-pkgs.org/data.html). 

Once we have an example dataset, it should then be easy to write some examples to include in the Roxygen skeleton.

**Comment by SebCockerell** [comment]
@HorridTom for these examples, I'm still not sure for a P chart what I need to pass in to the function for y and n to not get any errors. Do you have any suggestions?

**Comment by HorridTom** [comment]
Hi @SebCockerell, this is an example from the AEtracker app:

```
autospc::plot_auto_SPC(df, 
                           x = Month_Start, 
                           y = Within_4h, 
                           n = Total_Att, 
                           chartType = "P'",
                           title = cht_title,
                           subtitle = paste0(levelTitle, pr_name, typeTitle, reportingTitle),
                           override_x_title = x_title,
                           override_y_title = "Percentage within 4 hours")
```
