### ISSUE TITLE
Integer y values throw an error

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/autospc#20]
If the `y` column is an integer column (e.g. for a C chart) in the `df` argument of `plot_auto_SPC`, an error is thrown [here](https://github.com/HorridTom/spc-algorithm/blob/89ef5e70e04846c4d6dafb6bed15fd091cee29d4/R/functions.R#L49) because the `qic` [call](https://github.com/HorridTom/spc-algorithm/blob/89ef5e70e04846c4d6dafb6bed15fd091cee29d4/R/functions.R#L22) converts the y column to a double, resulting in a type conflict in `if_else` between `y.x` and `y.y`.

One approach would be to coerce the output of `qic` back to whatever type `y` was originally - but this may cause problems e.g. for u charts where the y coming out of `qic` may need to be a double even if the input was an integer.

Another approach would be to coerce any integer `y` to double at the start.

**Comment by ImogenConnorHelleur** [comment]
As the code runs qic several times and binds the results, it is best to have the input and output to qic in the same format.  I've forces y, n and b columns to be doubles but if for some reason the original type needs to be preserved in the output, I can write more code to convert back at the end of all the iterations.  Not sure why this would be needed, though, so will leave it for the moment.
