### ISSUE TITLE
Handle warnings in format_SPC function

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/autospc#45]
Warnings such as: Removed 28 row(s) containing missing values (geom_path)

Due to the use of NAs for getting discontinuous lines.  May be better to get data in longer format.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom, I didn't get any further with this since we spoke this morning. I've pushed my code to the bug-fix-plot-aesthetics branch with what I was trying commented out in the `format_spc()` function.  Feel free to get rid of those if you find a better way.  Also, you will probably want to change the `reshape2::melt()` into a `pivot_longer`.

**Comment by HorridTom** [comment]
Hi @ImogenConnorHelleur just checking, is this one with me still? Will try to push along soon if so.

**Comment by ImogenConnorHelleur** [comment]
@HorridTom , Yes I think so.
