### ISSUE TITLE
Unusual recalculation behaviour - any modifications needed?

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/autospc#46]
![2021-09-28-eng-all-recalc](https://user-images.githubusercontent.com/8202350/135080200-91942286-cce9-452d-a7a0-c5092c143292.png)

In this example from the AE Tracker app, the last recalculation appears to happen in an unusual place - we should investigate this to see if anything needs adapting...

**Comment by HorridTom** [comment]
In particular, from the strat of the final calculation period, I only count 7 points above the previous centre line. And looks like there is a rule break back towards the original process...

**Comment by ImogenConnorHelleur** [comment]
Hi Tom, I'll look into this.  My first thoughts are that the tracker is either using an old version of the algorithm or that the settings are different to what we use now (e.g. no regrets).
